

# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/files/cv.pdf` and uncomment the lines below.
[[main]]
  name = "CV"
  url = "/etcheverry_cv.pdf"
  weight = 4
  
  
  [[main]]
  name = "Contact"
  url = "/contact/"
  weight = 5
  

